// Replace the getEmptyAssessmentTemplate() function in api/assessment/index.js with this:

function getEmptyAssessmentTemplate() {
    return {
        "Conditional Access and Authentication": [
            {
                id: "ca_001",
                name: "CT Baseline - Require MFA For Admins",
                description: "Admin accounts are high-value targets for attackers. This policy ensures all administrative accounts must use multi-factor authentication.",
                userImpact: "Admins are required to use MFA, which adds some extra steps during login but significantly improves security.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_002",
                name: "Block Legacy Authentication",
                description: "Legacy authentication protocols don't support MFA and pose security risks.",
                userImpact: "Users using older email clients may need to update their applications or configuration.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_003",
                name: "Require MFA for All Users",
                description: "Multi-factor authentication for all user accounts accessing cloud services.",
                userImpact: "All users will need to set up and use MFA for accessing Microsoft 365 services.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_004",
                name: "Block Access from Unknown Locations",
                description: "Prevent access from suspicious geographic locations.",
                userImpact: "Users traveling to new locations may need to verify their identity through additional steps.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_005",
                name: "Require Compliant Devices",
                description: "Only allow access from devices that meet compliance requirements.",
                userImpact: "Devices must be enrolled in device management and meet security requirements.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_006",
                name: "Session Controls for High-Risk Users",
                description: "Apply additional monitoring and controls for users flagged as high-risk.",
                userImpact: "High-risk users may experience additional authentication prompts and limited access.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_007",
                name: "Block Access from Tor Networks",
                description: "Prevent access from anonymous networks that could be used maliciously.",
                userImpact: "Users attempting to access services through Tor or VPN networks may be blocked.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_008",
                name: "Require Password Change for High-Risk Sign-ins",
                description: "Force password changes when risky sign-in behavior is detected.",
                userImpact: "Users with suspicious sign-in patterns will need to change their passwords.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_009",
                name: "App Protection Policies for Mobile",
                description: "Require app protection policies for mobile device access.",
                userImpact: "Mobile users must use managed apps with data protection policies enabled.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_010",
                name: "Terms of Use Acceptance",
                description: "Require users to accept terms of use before accessing resources.",
                userImpact: "Users will need to review and accept updated terms of use periodically.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_011",
                name: "Block Access from Unmanaged Devices",
                description: "Prevent access from devices not managed by the organization.",
                userImpact: "Personal devices may be blocked from accessing corporate resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_012",
                name: "Require Hybrid Azure AD Join",
                description: "Ensure devices are properly joined to both on-premises and cloud domains.",
                userImpact: "Devices must be properly configured and joined to access resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_013",
                name: "Application Enforcement for Sensitive Apps",
                description: "Apply stricter controls for accessing sensitive applications.",
                userImpact: "Access to sensitive applications may require additional authentication steps.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_014",
                name: "Sign-in Frequency Controls",
                description: "Control how frequently users must re-authenticate.",
                userImpact: "Users may need to sign in more frequently for security purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_015",
                name: "Persistent Browser Session Controls",
                description: "Manage browser session persistence for security.",
                userImpact: "Browser sessions may expire more frequently requiring re-authentication.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_016",
                name: "Cloud App Security Integration",
                description: "Integrate with Microsoft Cloud App Security for enhanced monitoring.",
                userImpact: "Additional monitoring and potential restrictions on cloud app usage.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_017",
                name: "Guest User Access Controls",
                description: "Apply specific access controls for guest users.",
                userImpact: "External users may face additional restrictions when accessing resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_018",
                name: "Device State-Based Access",
                description: "Grant access based on device compliance and health status.",
                userImpact: "Non-compliant devices may be blocked from accessing resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_019",
                name: "Network Location-Based Controls",
                description: "Apply different access controls based on network location.",
                userImpact: "Access controls may vary depending on network location (office vs. home).",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ca_020",
                name: "Real-time Risk Assessment",
                description: "Use real-time risk signals to make access decisions.",
                userImpact: "Access may be granted or denied based on real-time risk assessment.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Identity and Access Management": [
            {
                id: "iam_001",
                name: "Enable Azure AD Password Protection",
                description: "Prevent users from using commonly compromised passwords.",
                userImpact: "Users cannot set passwords that appear on common password lists or contain company-specific terms.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_002",
                name: "Configure Password Complexity Requirements",
                description: "Enforce strong password policies across the organization.",
                userImpact: "Users must create passwords meeting complexity requirements (length, character types).",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_003",
                name: "Enable Self-Service Password Reset",
                description: "Allow users to reset their own passwords securely.",
                userImpact: "Users can reset passwords without contacting IT, but must register security information.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_004",
                name: "Implement Privileged Identity Management",
                description: "Just-in-time access for administrative roles.",
                userImpact: "Administrators must request and justify elevated access when needed.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_005",
                name: "Configure Access Reviews",
                description: "Regular reviews of user access rights and group memberships.",
                userImpact: "Managers will receive periodic requests to review team member access rights.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_006",
                name: "Enable Identity Protection Policies",
                description: "Automated risk-based access decisions using AI and machine learning.",
                userImpact: "Users may face additional authentication challenges if unusual activity is detected.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_007",
                name: "Configure Emergency Access Accounts",
                description: "Break-glass accounts for emergency situations.",
                userImpact: "No direct user impact, but ensures business continuity during emergencies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_008",
                name: "Implement Dynamic Groups",
                description: "Automatically manage group memberships based on user attributes.",
                userImpact: "Users may automatically gain or lose access to resources based on their role or department.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_009",
                name: "Configure Guest User Restrictions",
                description: "Limit what external users can access and see in the directory.",
                userImpact: "External partners and guests will have restricted visibility of organizational information.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_010",
                name: "Enable User Risk Policies",
                description: "Automatically respond to users flagged as high-risk.",
                userImpact: "High-risk users may be required to change passwords or face access restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_011",
                name: "Configure Sign-in Risk Policies",
                description: "Respond to risky sign-in attempts automatically.",
                userImpact: "Unusual sign-in attempts may trigger additional verification steps.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_012",
                name: "Implement Conditional Access Templates",
                description: "Use pre-configured security templates for common scenarios.",
                userImpact: "Standardized security controls may affect how users access resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_013",
                name: "Configure Authentication Strength",
                description: "Define different authentication requirements for different scenarios.",
                userImpact: "Some scenarios may require stronger authentication methods than others.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_014",
                name: "Enable Continuous Access Evaluation",
                description: "Real-time evaluation of access tokens for security changes.",
                userImpact: "Users may be logged out immediately if security conditions change.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_015",
                name: "Configure Administrative Unit Management",
                description: "Delegate administrative permissions for specific organizational units.",
                userImpact: "Administrative access will be more granular and limited to specific areas.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_016",
                name: "Implement Identity Governance",
                description: "Automate identity lifecycle management processes.",
                userImpact: "Account provisioning and deprovisioning will be more automated and timely.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_017",
                name: "Configure Entitlement Management",
                description: "Self-service access package requests and approvals.",
                userImpact: "Users can request access to resources through self-service portals.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "iam_018",
                name: "Enable Terms of Use Tracking",
                description: "Track and enforce acceptance of organizational terms of use.",
                userImpact: "Users must accept terms of use and re-accept when updated.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Microsoft Defender and Security": [
            {
                id: "mds_001",
                name: "Enable Microsoft Defender for Office 365",
                description: "Advanced threat protection for email and collaboration tools.",
                userImpact: "Enhanced protection against phishing and malware with minimal user disruption.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_002",
                name: "Configure Safe Attachments",
                description: "Scan email attachments in a secure sandbox environment.",
                userImpact: "Slight delay in email delivery while attachments are scanned for threats.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_003",
                name: "Configure Safe Links",
                description: "Rewrite URLs in emails and documents to check for malicious content.",
                userImpact: "URLs in emails may be rewritten and checked before allowing access.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_004",
                name: "Enable Anti-Phishing Policies",
                description: "Protect against impersonation and spoofing attacks.",
                userImpact: "Suspicious emails may be quarantined or marked with warnings.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_005",
                name: "Configure Attack Simulation Training",
                description: "Simulate phishing attacks to train users on security awareness.",
                userImpact: "Users will receive simulated phishing emails as part of security training.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_006",
                name: "Enable Microsoft Defender for Endpoint",
                description: "Advanced endpoint detection and response capabilities.",
                userImpact: "Enhanced monitoring and protection of devices with minimal performance impact.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_007",
                name: "Configure Automated Investigation and Response",
                description: "Automatically investigate and respond to security threats.",
                userImpact: "Automated responses to threats may temporarily affect system performance.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_008",
                name: "Enable Microsoft Defender for Cloud Apps",
                description: "Monitor and protect cloud application usage.",
                userImpact: "Cloud application usage will be monitored and may be restricted based on policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_009",
                name: "Configure Threat Hunting",
                description: "Proactive threat hunting capabilities across the environment.",
                userImpact: "No direct user impact, but enhanced security monitoring in the background.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_010",
                name: "Enable Microsoft Defender for Identity",
                description: "Monitor and protect hybrid identity infrastructure.",
                userImpact: "Enhanced monitoring of authentication and access patterns.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_011",
                name: "Configure Security Baselines",
                description: "Apply Microsoft-recommended security configurations.",
                userImpact: "System configurations may be changed to align with security best practices.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_012",
                name: "Enable Vulnerability Management",
                description: "Continuous assessment and management of security vulnerabilities.",
                userImpact: "Systems may require updates and patches more frequently.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_013",
                name: "Configure Incident Response",
                description: "Automated and manual incident response procedures.",
                userImpact: "Users may be notified of security incidents and required actions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_014",
                name: "Enable Microsoft Sentinel",
                description: "Cloud-native SIEM and SOAR solution for security monitoring.",
                userImpact: "Enhanced security monitoring with minimal direct user impact.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_015",
                name: "Configure Threat Intelligence",
                description: "Integrate threat intelligence feeds for enhanced protection.",
                userImpact: "Better protection against known threats with no direct user impact.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_016",
                name: "Enable Advanced Hunting",
                description: "Query-based threat hunting across Microsoft 365 data.",
                userImpact: "No direct user impact, but enhanced threat detection capabilities.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_017",
                name: "Configure Security Score Monitoring",
                description: "Continuous monitoring and improvement of security posture.",
                userImpact: "Security improvements may require user cooperation and adaptation.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "mds_018",
                name: "Enable Custom Detection Rules",
                description: "Create custom rules for detecting organization-specific threats.",
                userImpact: "Enhanced detection of threats specific to organizational environment.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Data Loss Prevention and Compliance": [
            {
                id: "dlp_001",
                name: "Configure Data Loss Prevention Policies",
                description: "Prevent sensitive data from being shared inappropriately.",
                userImpact: "Restrictions on sharing sensitive information via email and cloud services.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_002",
                name: "Enable Sensitive Information Types",
                description: "Automatically detect and classify sensitive information.",
                userImpact: "Documents containing sensitive information may be flagged or restricted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_003",
                name: "Configure Content Explorer",
                description: "Monitor and manage sensitive content across the organization.",
                userImpact: "Enhanced visibility into sensitive content usage with potential access restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_004",
                name: "Implement Retention Policies",
                description: "Automatically manage content lifecycle and retention.",
                userImpact: "Content may be automatically deleted or retained based on organizational policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_005",
                name: "Enable Communication Compliance",
                description: "Monitor and review organizational communications for policy violations.",
                userImpact: "Communications may be monitored and reviewed for compliance purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_006",
                name: "Configure Information Barriers",
                description: "Prevent inappropriate communications between specific groups.",
                userImpact: "Some users may be restricted from communicating with certain other users or groups.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_007",
                name: "Implement Records Management",
                description: "Manage regulatory and business-critical records.",
                userImpact: "Certain documents may be designated as records and have restricted modification or deletion.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_008",
                name: "Enable Advanced Data Governance",
                description: "Intelligent data classification and governance capabilities.",
                userImpact: "Data may be automatically classified and governed based on content and context.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_009",
                name: "Configure Insider Risk Management",
                description: "Detect and manage insider threats and risky behavior.",
                userImpact: "User activities may be monitored for potential insider risks.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_010",
                name: "Implement Customer Key",
                description: "Enhanced encryption key management for sensitive data.",
                userImpact: "Additional security for sensitive data with potential access complexity.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_011",
                name: "Enable Double Key Encryption",
                description: "Dual-key encryption for highly sensitive content.",
                userImpact: "Highly sensitive content may require additional keys for access.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_012",
                name: "Configure Audit Logging",
                description: "Comprehensive logging of user and administrative activities.",
                userImpact: "User activities will be logged for security and compliance purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_013",
                name: "Implement eDiscovery",
                description: "Legal hold and discovery capabilities for compliance requirements.",
                userImpact: "Content may be preserved for legal purposes and cannot be deleted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_014",
                name: "Enable Privileged Access Management",
                description: "Enhanced controls for privileged access to sensitive systems.",
                userImpact: "Privileged users will face additional access controls and monitoring.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_015",
                name: "Configure Data Connectors",
                description: "Import and manage data from various sources for compliance.",
                userImpact: "Data from external sources may be subject to organizational policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_016",
                name: "Implement Compliance Manager",
                description: "Centralized compliance assessment and management.",
                userImpact: "Compliance requirements may affect how users handle and store data.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_017",
                name: "Enable Content Search",
                description: "Advanced search capabilities across organizational content.",
                userImpact: "Content may be indexed and searchable for compliance and legal purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dlp_018",
                name: "Configure Sensitivity Labels",
                description: "Classify and protect content based on sensitivity levels.",
                userImpact: "Users must classify content and follow protection requirements based on sensitivity.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Device Management and Security": [
            {
                id: "dms_001",
                name: "Implement Microsoft Intune Device Management",
                description: "Comprehensive mobile device and application management.",
                userImpact: "Devices must be enrolled and managed, with potential restrictions on device usage.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_002",
                name: "Configure Device Compliance Policies",
                description: "Ensure devices meet organizational security requirements.",
                userImpact: "Non-compliant devices may be blocked from accessing organizational resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_003",
                name: "Enable Conditional Access for Devices",
                description: "Grant access based on device compliance and risk status.",
                userImpact: "Access to resources depends on device health and compliance status.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_004",
                name: "Implement App Protection Policies",
                description: "Protect organizational data within mobile applications.",
                userImpact: "Restrictions on copying, saving, and sharing data from managed applications.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_005",
                name: "Configure Windows Hello for Business",
                description: "Biometric and PIN-based authentication for Windows devices.",
                userImpact: "Users can use biometric authentication instead of traditional passwords.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_006",
                name: "Enable BitLocker Drive Encryption",
                description: "Encrypt device storage to protect data at rest.",
                userImpact: "Device performance may be slightly impacted during initial encryption process.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_007",
                name: "Configure Windows Defender Antivirus",
                description: "Built-in antivirus protection for Windows devices.",
                userImpact: "Real-time scanning may occasionally impact system performance.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_008",
                name: "Implement Windows Update for Business",
                description: "Managed deployment of Windows updates across the organization.",
                userImpact: "Updates will be deployed according to organizational schedule, potentially requiring restarts.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_009",
                name: "Enable Windows Information Protection",
                description: "Protect corporate data on Windows devices.",
                userImpact: "Corporate data will be separated from personal data with access restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_010",
                name: "Configure Microsoft Tunnel",
                description: "VPN gateway solution for mobile device access.",
                userImpact: "Mobile devices may require VPN connection for accessing internal resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_011",
                name: "Implement Endpoint Analytics",
                description: "Monitor and analyze device performance and user experience.",
                userImpact: "Device usage and performance data will be collected for analysis.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_012",
                name: "Enable Remote Wipe Capabilities",
                description: "Ability to remotely wipe corporate data from devices.",
                userImpact: "Corporate data can be remotely removed from lost or compromised devices.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_013",
                name: "Configure Device Enrollment Restrictions",
                description: "Control which devices can be enrolled in management.",
                userImpact: "Only approved device types and platforms can access corporate resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_014",
                name: "Implement Co-Management with SCCM",
                description: "Hybrid management of devices using both Intune and SCCM.",
                userImpact: "Devices will be managed by multiple systems with potentially different policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_015",
                name: "Enable Windows Autopilot",
                description: "Automated device deployment and configuration.",
                userImpact: "New devices will be automatically configured with minimal user intervention.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_016",
                name: "Configure Device Certificates",
                description: "Deploy and manage certificates for device authentication.",
                userImpact: "Devices will use certificates for secure authentication to network resources.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_017",
                name: "Implement Mobile Application Management",
                description: "Manage and secure mobile applications without full device enrollment.",
                userImpact: "Work-related mobile apps will be managed and may have usage restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "dms_018",
                name: "Enable Compliance Grace Period",
                description: "Allow time for users to remediate compliance issues.",
                userImpact: "Users will have a grace period to fix compliance issues before access is blocked.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Email and Communication Security": [
            {
                id: "ecs_001",
                name: "Configure Exchange Online Protection",
                description: "Built-in email filtering and anti-malware protection.",
                userImpact: "Enhanced email security with potential delays for suspicious messages.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_002",
                name: "Implement DKIM Email Authentication",
                description: "DomainKeys Identified Mail for email authenticity verification.",
                userImpact: "Outbound emails will be signed for authentication, improving delivery reliability.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_003",
                name: "Configure SPF Records",
                description: "Sender Policy Framework to prevent email spoofing.",
                userImpact: "Improved protection against spoofed emails claiming to be from your domain.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_004",
                name: "Implement DMARC Policy",
                description: "Domain-based Message Authentication, Reporting & Conformance.",
                userImpact: "Enhanced email authentication with reports on potential spoofing attempts.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_005",
                name: "Enable Mail Flow Rules",
                description: "Automated email processing and security rules.",
                userImpact: "Emails may be automatically processed, quarantined, or redirected based on content.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_006",
                name: "Configure Quarantine Policies",
                description: "Manage quarantined messages and user access.",
                userImpact: "Users may need to review quarantined messages and request release.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_007",
                name: "Implement Message Encryption",
                description: "Automatic encryption of sensitive email content.",
                userImpact: "Sensitive emails may be automatically encrypted, requiring additional steps to read.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_008",
                name: "Enable Safe Sender Lists",
                description: "Manage trusted sender lists and exceptions.",
                userImpact: "Emails from trusted senders will bypass certain security checks.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_009",
                name: "Configure Anti-Spam Policies",
                description: "Advanced spam filtering and bulk mail handling.",
                userImpact: "Improved spam filtering may occasionally catch legitimate emails.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_010",
                name: "Implement Shared Mailbox Security",
                description: "Enhanced security controls for shared mailboxes.",
                userImpact: "Shared mailbox access may require additional authentication or permissions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_011",
                name: "Enable Teams Security Features",
                description: "Security enhancements for Microsoft Teams communications.",
                userImpact: "Teams communications may have additional security restrictions and monitoring.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_012",
                name: "Configure External Sharing Policies",
                description: "Control how content is shared with external users.",
                userImpact: "Restrictions on sharing content with external users and partners.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_013",
                name: "Implement Email Disclaimers",
                description: "Automatic addition of legal and security disclaimers to emails.",
                userImpact: "Outbound emails will include organizational disclaimers and warnings.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_014",
                name: "Enable Litigation Hold",
                description: "Preserve email content for legal and compliance purposes.",
                userImpact: "Email content may be preserved and cannot be permanently deleted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_015",
                name: "Configure Message Trace",
                description: "Track email delivery and investigate mail flow issues.",
                userImpact: "Email delivery paths and status will be tracked for troubleshooting.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_016",
                name: "Implement Calendar Sharing Restrictions",
                description: "Control how calendar information is shared externally.",
                userImpact: "Limitations on sharing calendar details with external users.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_017",
                name: "Enable Teams Meeting Security",
                description: "Enhanced security controls for Teams meetings and calls.",
                userImpact: "Teams meetings may have lobby requirements and recording restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "ecs_018",
                name: "Configure Mobile Email Policies",
                description: "Security policies specifically for mobile email access.",
                userImpact: "Mobile email access may have additional security requirements and restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Cloud App Security and Governance": [
            {
                id: "cas_001",
                name: "Enable Microsoft Cloud App Security",
                description: "Comprehensive cloud application security and monitoring.",
                userImpact: "Cloud application usage will be monitored and may be restricted based on policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_002",
                name: "Configure Shadow IT Discovery",
                description: "Identify and manage unsanctioned cloud applications.",
                userImpact: "Unsanctioned cloud applications may be blocked or require approval for use.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_003",
                name: "Implement App Governance",
                description: "Monitor and govern third-party applications accessing Microsoft 365.",
                userImpact: "Third-party app permissions may be reviewed and potentially revoked.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_004",
                name: "Configure Cloud App Policies",
                description: "Automated policies for cloud application behavior and access.",
                userImpact: "Cloud application access may be automatically controlled based on behavior patterns.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_005",
                name: "Enable Session Controls",
                description: "Real-time monitoring and control of cloud app sessions.",
                userImpact: "Cloud application sessions may be monitored and controlled in real-time.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_006",
                name: "Implement Data Governance Framework",
                description: "Comprehensive governance of data across cloud services.",
                userImpact: "Data handling and storage will be governed by organizational policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_007",
                name: "Configure API Security",
                description: "Monitor and secure API access to cloud applications.",
                userImpact: "API access to cloud services may be monitored and restricted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_008",
                name: "Enable Cloud Discovery Reports",
                description: "Regular reporting on cloud application usage and risks.",
                userImpact: "Cloud application usage patterns will be analyzed and reported.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_009",
                name: "Implement Zero Trust for Apps",
                description: "Zero trust security model for cloud application access.",
                userImpact: "All cloud application access will be verified and potentially restricted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_010",
                name: "Configure Risk Scoring",
                description: "Automated risk assessment for cloud applications and users.",
                userImpact: "Application and user risk scores may affect access permissions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_011",
                name: "Enable Anomaly Detection",
                description: "Machine learning-based detection of unusual user behavior.",
                userImpact: "Unusual behavior patterns may trigger security alerts and restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_012",
                name: "Implement OAuth App Monitoring",
                description: "Monitor and control OAuth application permissions.",
                userImpact: "OAuth app permissions will be monitored and may require approval.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_013",
                name: "Configure File Activity Monitoring",
                description: "Monitor file access and sharing activities across cloud services.",
                userImpact: "File access and sharing activities will be monitored and potentially restricted.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_014",
                name: "Enable Threat Protection for SaaS",
                description: "Advanced threat protection for Software-as-a-Service applications.",
                userImpact: "Enhanced security for SaaS applications with potential access delays.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_015",
                name: "Implement Cloud App Catalog Management",
                description: "Maintain a catalog of approved and restricted cloud applications.",
                userImpact: "Access to cloud applications will be controlled based on approval status.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_016",
                name: "Configure Data Residency Controls",
                description: "Control where organizational data is stored geographically.",
                userImpact: "Data storage locations may be restricted based on compliance requirements.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "cas_017",
                name: "Enable Cloud Workload Protection",
                description: "Security monitoring and protection for cloud workloads.",
                userImpact: "Cloud workloads will have enhanced monitoring and security controls.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ],
        "Network and Infrastructure Security": [
            {
                id: "nis_001",
                name: "Implement Network Segmentation",
                description: "Logical separation of network resources for enhanced security.",
                userImpact: "Network access may be restricted based on user role and device location.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_002",
                name: "Configure Azure AD Connect Security",
                description: "Secure hybrid identity synchronization between on-premises and cloud.",
                userImpact: "Enhanced security for identity synchronization with potential authentication delays.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_003",
                name: "Enable VPN Security Controls",
                description: "Enhanced security controls for VPN access.",
                userImpact: "VPN access may require additional authentication and have usage restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_004",
                name: "Implement DNS Filtering",
                description: "Filter DNS requests to block malicious and inappropriate websites.",
                userImpact: "Access to certain websites may be blocked based on security and policy requirements.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_005",
                name: "Configure Firewall Policies",
                description: "Comprehensive firewall rules for network traffic control.",
                userImpact: "Network traffic may be restricted based on security policies.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_006",
                name: "Enable Network Monitoring",
                description: "Continuous monitoring of network traffic and behavior.",
                userImpact: "Network activities will be monitored for security and compliance purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_007",
                name: "Implement Secure Wi-Fi Policies",
                description: "Enhanced security controls for wireless network access.",
                userImpact: "Wi-Fi access may require device certificates and have usage restrictions.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_008",
                name: "Configure Network Access Control",
                description: "Control device access to network resources based on compliance.",
                userImpact: "Network access depends on device compliance and health status.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_009",
                name: "Enable Azure Bastion",
                description: "Secure remote access to Azure virtual machines.",
                userImpact: "Remote access to cloud resources will use secure gateway connections.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_010",
                name: "Implement Zero Trust Network Access",
                description: "Never trust, always verify approach to network access.",
                userImpact: "All network access will be verified and potentially restricted regardless of location.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_011",
                name: "Configure Network Security Groups",
                description: "Define security rules for network traffic in Azure.",
                userImpact: "Network traffic in cloud environments will be controlled by security rules.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_012",
                name: "Enable DDoS Protection",
                description: "Protection against distributed denial of service attacks.",
                userImpact: "Enhanced protection against network attacks with minimal impact on normal operations.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_013",
                name: "Implement Network Encryption",
                description: "Encrypt network traffic to protect data in transit.",
                userImpact: "Network communications will be encrypted, potentially affecting performance.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_014",
                name: "Configure Private Endpoints",
                description: "Private network access to Azure services.",
                userImpact: "Cloud services will be accessed through private network connections.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            },
            {
                id: "nis_015",
                name: "Enable Traffic Analytics",
                description: "Analyze network traffic patterns for security insights.",
                userImpact: "Network traffic patterns will be analyzed for security and optimization purposes.",
                tech: "",
                status: null,
                clientApproval: null,
                notes: "",
                rolloutDate: ""
            }
        ]
    };
}